# Generated by Django 5.2.8 on 2025-11-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='სახელი')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='სურათი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='დასახელება')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('stock', models.IntegerField(default=0, verbose_name='მარაგი')),
                ('is_available', models.BooleanField(default=True, verbose_name='ხელმისაწვდომი')),
                ('featured', models.BooleanField(default=False, verbose_name='გამორჩეული')),
                ('color', models.CharField(choices=[('white', 'თეთრი'), ('black', 'შავი'), ('brown', 'ყავისფერი'), ('gray', 'ნაცრისფერი'), ('beige', 'ბეჟი'), ('red', 'წითელი'), ('blue', 'ლურჯი'), ('green', 'მწვანე')], max_length=20, verbose_name='ფერი')),
                ('material', models.CharField(choices=[('wood', 'ხე'), ('metal', 'ლითონი'), ('glass', 'მინა'), ('leather', 'ტყავი'), ('textile', 'ტექსტილი'), ('plastic', 'პლასტიკი')], max_length=20, verbose_name='მასალა')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name': 'პროდუქტი',
                'verbose_name_plural': 'პროდუქტები',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='სურათი')),
                ('is_main', models.BooleanField(default=False, verbose_name='მთავარი სურათი')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='პროდუქტი')),
            ],
            options={
                'verbose_name': 'პროდუქტის სურათი',
                'verbose_name_plural': 'პროდუქტის სურათები',
            },
        ),
    ]
