# Generated by Django 5.2.8 on 2025-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
            ],
            options={
                'verbose_name': 'კალათა',
                'verbose_name_plural': 'კალათები',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='რაოდენობა')),
            ],
            options={
                'verbose_name': 'კალათის პროდუქტი',
                'verbose_name_plural': 'კალათის პროდუქტები',
            },
        ),
    ]
