# Generated by Django 5.2.8 on 2025-11-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='შეკვეთის ნომერი')),
                ('status', models.CharField(choices=[('pending', 'მიმდინარე'), ('processing', 'მუშავდება'), ('shipped', 'გაგზავნილი'), ('delivered', 'მიტანილი'), ('cancelled', 'გაუქმებული')], default='pending', max_length=20, verbose_name='სტატუსი')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ჯამური თანხა')),
                ('shipping_address', models.TextField(verbose_name='მიწოდების მისამართი')),
                ('phone', models.CharField(max_length=20, verbose_name='ტელეფონი')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='შენიშვნები')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
            ],
            options={
                'verbose_name': 'შეკვეთა',
                'verbose_name_plural': 'შეკვეთები',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='რაოდენობა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი შეკვეთის დროს')),
            ],
            options={
                'verbose_name': 'შეკვეთის პროდუქტი',
                'verbose_name_plural': 'შეკვეთის პროდუქტები',
            },
        ),
    ]
